[package]
name = "quickpython-llm"
version = "0.1.0"
edition = "2024"

[dependencies]
quickpython = { path = ".." }
reqwest = { version = "0.13.2", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
